FROM envoyproxy/envoy:v1.17.0

RUN apt-get update
RUN apt install -y net-tools wget
RUN mkdir /var/log/envoy/
COPY ./bin/service /usr/local/bin/srv
COPY ./bin/grpcurl /tmp/grpcurl
COPY ./script/grpc_start /etc/grpc_start
CMD /etc/grpc_start

